package endurteam.overwhelmed.entity.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class SnailAnimations {
        public static final Animation WALKING = Animation.Builder.create(2f).looping()
                .addBoneAnimation("shell",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("shell",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("left_antenna",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(-1f, 0f, -3f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("left_antenna",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 22.5f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("left_antenna",
                        new Transformation(Transformation.Targets.SCALE,
                                new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1f, 1.2f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("right_antenna",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(1f, 0f, -3f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("right_antenna",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, -22.5f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("right_antenna",
                        new Transformation(Transformation.Targets.SCALE,
                                new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1f, 1.2f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("body",
                        new Transformation(Transformation.Targets.SCALE,
                                new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createScalingVector(0.8f, 1.1f, 1.2f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("saddle",
                        new Transformation(Transformation.Targets.TRANSLATE,
                                new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("saddle",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC))).build();
        public static final Animation IDLING = Animation.Builder.create(2f).looping()
                .addBoneAnimation("left_antenna",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, -20f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("left_antenna",
                        new Transformation(Transformation.Targets.SCALE,
                                new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1f, 1.3f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("right_antenna",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 20f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("right_antenna",
                        new Transformation(Transformation.Targets.SCALE,
                                new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1f, 1.3f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("body",
                        new Transformation(Transformation.Targets.SCALE,
                                new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createScalingVector(1.1f, 0.9f, 1f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("shell",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC)))
                .addBoneAnimation("saddle",
                        new Transformation(Transformation.Targets.ROTATE,
                                new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(1f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC),
                                new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                        Transformation.Interpolations.CUBIC))).build();

}